version: '3'

services:

  db:
    build: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "info"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes: 
      - .data:/data
      
  app:
    build: app
    restart: on-failure
    ports: 
      - "8000:8000"
    depends_on:
      - db
